# Generated by Django 6.0.2 on 2026-03-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options'),
        ('scrun_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='members.organization'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='scrun_master.project'),
        ),
    ]
