# Generated by Django 6.0.2 on 2026-04-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options'),
        ('scrun_master', '0002_alter_project_organization_alter_teammember_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmember',
            old_name='invited_at',
            new_name='joined_at',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='invited',
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrun_master.project')),
            ],
        ),
    ]
